spring:
  application:
    name: eureka3
  boot:
    admin:
      context-path: /admin
server:
  port: 8073
eureka:
  instance:
    hostname: eureka3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka1:8070/eureka/,http://eureka2:8072/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5


management:
  endpoints:
    web:
      exposure:
        include: "*"
   
